const ACTION_TYPE = {

  /** *****************************************
   * APP Actions
   */
  INIT_APP_CONFIG: 'app/INIT_APP_CONFIG',
  UPDATE_ROUTER: 'app/UPDATE_ROUTER',

  // Vaildate
  START_VALIDATE_ALL: 'app/START_VALIDATE_ALL',
  RESET_VAILDATE_MSG: 'app/RESET_VAILDATE_MSG',
  REPORT_VALID_ERROR: 'app/REPORT_VALID_ERROR',

  // Ajax
  REQUEST_SAVE: 'app/REQUEST_SAVE',
  RECEIVE_SAVE: 'app/RECEIVE_SAVE',
  RQ_FETCH: 'app/RQ_FETCH',
  RC_FETCH: 'app/RC_FETCH',
  RECEIVE_AJAX_ERROR: 'app/RECEIVE_AJAX_ERROR',
  RECEIVE_SERVER_ERROR: 'app/RECEIVE_SERVER_ERROR',

  // Login
  CHANGE_LOGIN_STATUS: 'app/CHANGE_LOGIN_STATUS',
  CHANGE_LOGIN_STATE: 'app/CHANGE_LOGIN_STATE',

  // 常用操作
  REFRESH_ALL: 'app/REFRESH_ALL',
  REQUEST_FETCH_AC_INFO: 'app/REQUEST_FETCH_AC_INFO',
  RECIVECE_FETCH_AC_INFO: 'app/RECIVECE_FETCH_AC_INFO',

  // Model框
  CREATE_MODAL: 'app/CREATE_MODAL',
  CHANGE_MODAL_STATE: 'app/CHANGE_MODAL_STATE',


  /** *****************************************
   * Screen Actions
   */
  INIT_SCREEN: 'screen/INIT',
  LEAVE_SCREEN: 'screen/LEAVE',

  // Ajax Fetch
  CHANGE_SCREEN_QUERY: 'screen/CHANGE_QUERY',
  REQEUST_FETCH_SCREEN_DATA: 'screen/REQEUST_FETCH_DATA',
  RECIVE_SCREEN_DATA: 'screen/RECIVE_DATA',

  // Ajax Save
  CHANGE_SCREEN_ACTION_QUERY: 'screen/CHANGE_ACTION_QUERY',

  // Screen Settings
  UPDATE_SCREEN_SETTINGS: 'screen/UPDATE_SETTINGS',

  // Screen List
  ADD_LIST_ITEM: 'screen/ADD_LIST_ITEM',
  ACTIVE_LIST_ITEM: 'screen/ACTIVE_LIST_ITEM',
  SELECT_LIST_ITEM: 'screen/SELECT_LIST_ITEM',
  UPDATE_CUR_EDIT_LIST_ITEM: 'screen/UPDATE_CUR_EDIT_LIST_ITEM',
  UPDATE_LIST_ITEM_BY_INDEX: 'screen/UPDATE_LIST_ITEM_BY_INDEX',
  CLOSE_LIST_ITEM_MODAL: 'screen/CLOSE_LIST_ITEM_MODAL',

  // Custom Props
  UPDATE_SCREEN_CUSTOM_PROPS: 'screen/UPDATE_CUSTOM_PROPS',


  /**
   * Property 属性列表
   */
  // 操作属性面板容器
  TOGGLE_PROPERTY: 'properties/TOGGLE_VISIBLE',

  // 操作属性面板
  INIT_PROPERTY_PANEL: 'properties/INIT_PANEL',
  COLLAPSE_PROPERTY_PANEL: 'properties/COLLAPSE_PANEL',
  REMOVE_PROPERTY_PANEL: 'properties/REMOVE_PANEL',

  // 修改属性面板内容
  CHANGE_PROPERTY_PANEL_ITEM: 'properties/CHANGE_PANEL_ITEM',
  CHANGE_PROPERTY_PANEL_DATA: 'properties/CHANGE_PANEL_DATA',

  // 接收属性面板数据 Data（从服务器端获取的数据）
  RC_PROPERTY_PANEL_DATA: 'properties/RECIVECE_PANEL_DATA',
};

export default ACTION_TYPE;

