const ACTION_TYPE = {

  /** *****************************************
   * APP Actions
   */
  INIT_APP_CONFIG: 'INIT_APP_CONFIG',

  // Vaildate
  START_VALIDATE_ALL: 'START_VALIDATE_ALL',
  RESET_VAILDATE_MSG: 'RESET_VAILDATE_MSG',
  REPORT_VALID_ERROR: 'REPORT_VALID_ERROR',

  // Ajax
  REQUEST_SAVE: 'REQUEST_SAVE',
  RECEIVE_SAVE: 'RECEIVE_SAVE',
  RQ_FETCH: 'RQ_FETCH',
  RC_FETCH: 'RC_FETCH',
  RECEIVE_AJAX_ERROR: 'RECEIVE_AJAX_ERROR',
  RECEIVE_SERVER_ERROR: 'RECEIVE_SERVER_ERROR',

  // Login
  CHANGE_LOGIN_STATUS: 'CHANGE_LOGIN_STATUS',
  CHANGE_LOGIN_STATE: 'CHANGE_LOGIN_STATE',

  // 常用操作
  REFRESH_ALL: 'REFRESH_ALL',
  REQUEST_FETCH_AC_INFO: 'REQUEST_FETCH_AC_INFO',
  RECIVECE_FETCH_AC_INFO: 'RECIVECE_FETCH_AC_INFO',

  // Model框
  CREATE_MODAL: 'CREATE_MODAL',
  CHANGE_MODAL_STATE: 'CHANGE_MODAL_STATE',


  /** *****************************************
   * Screen Actions
   */
  INIT_SCREEN: 'INIT_SCREEN',
  LEAVE_SCREEN: 'LEAVE_SCREEN',

  // Ajax Fetch
  CHANGE_SCREEN_QUERY: 'CHANGE_SCREEN_QUERY',
  REQEUST_FETCH_SCREEN_DATA: 'REQEUST_FETCH_SCREEN_DATA',
  RECIVE_SCREEN_DATA: 'RECIVE_SCREEN_DATA',

  // Ajax Save
  CHANGE_SCREEN_ACTION_QUERY: 'CHANGE_SCREEN_ACTION_QUERY',

  // Screen Settings
  UPDATE_SCREEN_SETTINGS: 'UPDATE_SCREEN_SETTINGS',

  // Screen List
  ADD_LIST_ITEM: 'ADD_LIST_ITEM',
  ACTIVE_LIST_ITEM: 'ACTIVE_LIST_ITEM',
  SELECT_LIST_ITEM: 'SELECT_LIST_ITEM',
  UPDATE_CUR_EDIT_LIST_ITEM: 'UPDATE_CUR_EDIT_LIST_ITEM',
  UPDATE_LIST_ITEM_BY_INDEX: 'UPDATE_LIST_ITEM_BY_INDEX',
  CLOSE_LIST_ITEM_MODAL: 'CLOSE_LIST_ITEM_MODAL',

  // Custom Props
  UPDATE_SCREEN_CUSTOM_PROPS: 'UPDATE_SCREEN_CUSTOM_PROPS',


  /**
   * Property 属性列表
   */
  // 操作属性面板容器
  TOGGLE_PROPERTY: 'TOGGLE_PROPERTY',

  // 操作属性面板
  INIT_PROPERTY_PANEL: 'INIT_PROPERTY_PANEL',
  COLLAPSE_PROPERTY_PANEL: 'COLLAPSE_PROPERTY_PANEL',
  REMOVE_PROPERTY_PANEL: 'REMOVE_PROPERTY_PANEL',

  // 修改属性面板内容
  CHANGE_PROPERTY_PANEL_ITEM: 'CHANGE_PROPERTY_PANEL_ITEM',
  CHANGE_PROPERTY_PANEL_DATA: 'CHANGE_PROPERTY_PANEL_DATA',

  // 接收属性面板数据 Data（从服务器端获取的数据）
  RC_PROPERTY_PANEL_DATA: 'RECIVECE_PROPERTY_PANEL_DATA',
};

export default ACTION_TYPE;

